= eefenn-cli
:toc:

== Install

[source, bash]
----
# clone this repository
git clone git@github.com:eefenn/eefenn-cli.git

# build the binary
go build -o eefenn-cli-install

# run the install command
./eefenn-cli-install install
----

This will create a directory at `/usr/lib/eefenn-cli` and create a directory for scripts and a file (`eefenn.config.json`) to configure the tool.

== What is eefenn-cli?

A tool to create and manage scripts - with a bit of extra convenience features.

It also provides a way to manage scripts that have filesystem dependencies, where the script is dependant on both file contents and file position relative to the script. An example would be a script that requires a file at the position _<script_working_directory>/subdirectory/<file>_.

== Seemless filesystem recreation

If the script depends on the file, this filesystem configuration can be committed to eefenn-cli, and the files can be removed. The command line interface for eefenn-cli creates the illusion of runing the script globally, with no issue of depndency positions. In reality it stores the configuration you previously committed, unpacks it at the current location, runs the command, and cleans up after seemlessly.

== Creating a command

=== Prerequisites: Config, and script position.

To create an eefenn-cli you have to create a *config.yaml file in the same directory as your script*.

Here is an example:

[source, bash]
----
(base) ➜  test-eefenn-cli tree
.
├── config.yaml
├── another_file.txt
├── echo-something.sh
└── something.txt

0 directories, 4 files
----

As you can see from the above snippet, the file `config.yaml` is in the same directory as `echo-something.sh`

=== Writing the config.yaml file

Here is an overview of the commands in an eefenn-cli _config.yaml_ file:

[options="header"]
[cols="1,1,3"]
|===
| Title | type | Description

| *name* | _string_ | The name of the command that you want to create. When you `commit` your command to eefenn-cli, you will be able to run it by the run subcommand.
| *script* | _file path_ | The name of the script that you want your command to be an alias of.
| *description* | _string_ | A description that you can use further down the line to describe what your command does.
| *needs* | _[]file path_ / nil | An array of paths to the files that the script depends on.
|===

== Example continued

In the above example, I wanted to create a script that just echoes the content of _something.txt_ to standard output. This means that I will need to specify all of this in my config file. In other words, my command's script depends on _something.txt_. I also want to call my new command '_cool-command_'. Here is my config file:

[source, yaml]
----
# A cool name for my command
name: cool-command

# The script for my command, relative to where this config.yaml file is.
script: ./echo-something.sh

# a description of what my command does.
description: "This command just echoes the content of a text file, which is saved as a dependency of this command."

# The dependencies of my script (in this case './echo-something.sh').
needs:
  - ./text.txt
----

==== Creating the command, by `ef commit`

To save your configuration so that you can use the command in future follow these steps:

1. Go to the directory that contains your command config.yaml

2. Run `ef commit`

3. _That's it!_

Now if you run your command from anywhere in your filesystem, it will recreate the directory structure your command relies on, execute your script, and clean up as if nothing happened.