= eefenn-cli
:toc:

A command line tool to automate eefenn tasks.

This command line tool supports utilities that essentially allows you to perform scripts based on subcommands. You can customize this tool, but it also comes with provided scripts, and subcommands.

== Install

[source, bash]
----
# clone this repository
git clone git@github.com:eefenn/eefenn-cli.git

# build the binary
go build -o eefenn-cli-install

# run the install command
./eefenn-cli-install install
----

This will create a directory at `/usr/lib/eefenn-cli` and create a directory for scripts and a file (`eefenn.config.json`) to configure the tool.

== Updating your tool to be up to date with remote scripts

To update the eefenn-cli tool with the remote repository, run the command:

[source, bash]
----
eefenn tidy
----

== Customizing the tool

You can customize this tool and add your own automation scripts. Each script will have

1. A *subcommand* for this cli tool.
2. A *description* of what the script for the command does.

=== How to add a subcommand

After you have the basic install done, you can customize your tool by adding a subcommand via the `eefenn asc` command:

[source, bash]
----
eefenn asc=my-command=./my-command-script.sh
----

==== What happens internally?

eefenn-cli will:

1. Parse your command.
2. Generate a unique hash for your custom command.
3. Create a JSON object for the command in `/usr/lib/eefenn/eefenn-cli.config.json`.

This object will look like this:

[source,json]
----
"my-command" : {
  "command-hash" : "b9f8c69c0e3e7f0f20d8e2b51c320a2f"
}
----

When you run your command hereafter, eefenn-cli will

a. Look in eefenn-cli.config.json and find your command.
b. Get the command-hash.
c. go to the directory created for your command-hash (in this case `/usr/lib/eefenn-cli/commands/b9f8c69c0e3e7f0f20d8e2b51c320a2f`)
d. This directory will look something like this:

----
b9f8c69c0e3e7f0f20d8e2b51c320a2f
├── b9f8c69c0e3e7f0f20d8e2b51c320a2f.dependencies
│   ├── file1.txt
│   └── file2.txt
└── b9f8c69c0e3e7f0f20d8e2b51c320a2f.sh

1 directory, 3 files
----

The script will use the files in the `<command-hash>.dependencies` directory to complete work in the script.