name: echo-something
script: write-something-to-stdout.sh
needs:
  - something-else.txt
description: Just echoes something
args:
  - name: something
    type: string
    description: Something to echo